### ISSUE TITLE
Unable to reconnect after device has been turned off

### ISSUE THREAD

**Issue by dkgof** [sanjay900/igrill#5]
After using the iGrill Mini, and turning it off, it does not reconnect when turned back on, it just stays in pairing/connect mode, blinking blue.

The logs give me the following error:

```Traceback (most recent call last):
File "/config/custom_components/igrill_ble/igrill.py", line 207, in async_init
await self.client.pair(protection_level=1)
File "/usr/local/lib/python3.10/site-packages/bleak/__init__.py", line 495, in pair
return await self._backend.pair(*args, **kwargs)
File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 407, in pair
assert_reply(reply)
File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/utils.py", line 20, in assert_reply
raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.InProgress] In Progress
2022-11-08 08:15:58.120 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved

Traceback (most recent call last):
File "/config/custom_components/igrill_ble/igrill.py", line 207, in async_init
await self.client.pair(protection_level=1)
File "/usr/local/lib/python3.10/site-packages/bleak/__init__.py", line 495, in pair
return await self._backend.pair(*args, **kwargs)
File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 407, in pair
assert_reply(reply)
File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/utils.py", line 20, in assert_reply
raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.AuthenticationFailed] Authentication Failed
```

If i go to the terminal, and write `bluetoothctl` and then `remove mydevicemac` it disconnects, and then immediately reconnects, and then it works from inside HA again.

**Comment by dkgof** [comment]
`bluetoothctl -version` gives me: 5.65, if that matters in any way.

**Comment by dkgof** [comment]
Unfortunately right now, after trying to turn it off and back on, even `bluetoothctl remove` does not make it work anymore, i just get another entry in the log, same as above each time.

**Comment by sanjay900** [comment]
https://github.com/sanjay900/igrill/issues/2
try this maybe?

**Comment by dkgof** [comment]
I tired all sorts of combinations of, remove, connect, trust, pair in bluetoothctl. But now it seems that i get authentication errors when doing a pair aswell in that utility, which makes me suspect that it is something with the bluetooth stack / driver, and not your component. It is weird that it worked the first 2 times, and now not at all.

**Comment by sanjay900** [comment]
I have in the past gotten to a point where all that would resolve connection issues was restarting home assistant os outright or restarting the bluetooth service

**Comment by dkgof** [comment]
I must admit that i gave up and installed the MQTT version again.
